# Generated by Django 4.2.8 on 2025-12-29 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0015_alter_buildingyearlyrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pangalan ng Pananim (e.g., Mangga)', max_length=255)),
                ('variety', models.CharField(blank=True, help_text='Uri (e.g., Piko, Indian)', max_length=100)),
                ('fruit_bearing', models.IntegerField(default=0, help_text='Nagbubunga')),
                ('non_fruit_bearing', models.IntegerField(default=0, help_text='Hindi Nagbubunga')),
                ('total_quantity', models.IntegerField(default=0, help_text='Kabuuang Bilang')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Halaga ng Bawat Puno', max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, help_text='Kabuuang Halaga', max_digits=12)),
                ('location', models.CharField(blank=True, help_text='Lokasyon (Brgy/Bayan)', max_length=255)),
                ('remarks', models.TextField(blank=True, help_text='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(blank=True, help_text='Local where plant is located', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='properties.local')),
            ],
            options={
                'verbose_name': 'Plant (Pananim)',
                'verbose_name_plural': 'Plants (Pananim)',
                'ordering': ['local', 'name'],
            },
        ),
    ]
