# Generated by Django 4.2.8 on 2025-12-26 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0015_alter_buildingyearlyrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, help_text='Location (e.g., Koro, Kalihiman)', max_length=100)),
                ('property_number', models.CharField(blank=True, help_text='Property Number / Item Code', max_length=50)),
                ('date_acquired', models.DateField(blank=True, help_text='Date acquired', null=True)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity (Col D)')),
                ('item_name', models.CharField(help_text='Item Name/Description (Col E)', max_length=255)),
                ('brand', models.CharField(blank=True, help_text='Brand (Col F)', max_length=100)),
                ('model', models.CharField(blank=True, help_text='Model (Col G)', max_length=100)),
                ('material', models.CharField(blank=True, help_text='Material (Col H)', max_length=100)),
                ('color', models.CharField(blank=True, help_text='Color (Col I)', max_length=50)),
                ('size', models.CharField(blank=True, help_text='Size (Col J)', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Unit Price (Col K)', max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Total Price (Col L)', max_digits=15)),
                ('reference_number', models.CharField(blank=True, help_text='Reference/Invoice Number (Col M)', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='Remarks/Status')),
                ('year_reported', models.IntegerField(help_text='Year reported')),
                ('is_new', models.BooleanField(default=False, help_text='True if new addition (Page 3)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(blank=True, help_text='Local where item is located', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='properties.local')),
            ],
            options={
                'verbose_name': 'Item (Kagamitan)',
                'verbose_name_plural': 'Items (Kagamitan)',
                'ordering': ['location', 'item_name'],
                'indexes': [models.Index(fields=['local', 'year_reported'], name='kagamitan_i_local_i_9de95f_idx'), models.Index(fields=['local', 'location'], name='kagamitan_i_local_i_8b10fd_idx')],
            },
        ),
    ]
