# Generated by Django 4.2.8 on 2025-12-29 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0015_alter_buildingyearlyrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Lokasyon', max_length=255)),
                ('lot_area', models.DecimalField(decimal_places=2, default=0, help_text='Sukat (sqm)', max_digits=12)),
                ('lot_type', models.CharField(blank=True, help_text='Uri ng Lupa (Res/Com/Agri/Inst)', max_length=100)),
                ('title_number', models.CharField(blank=True, help_text='TCT/OCT Number', max_length=100)),
                ('owner', models.CharField(blank=True, help_text='Nagmamay-ari', max_length=255)),
                ('status', models.CharField(choices=[('TITULADO', 'Titulado'), ('TAX_DEC', 'Tax Declaration'), ('OTHER', 'Other')], default='TITULADO', help_text='Kaurian (Titulado/Tax Dec)', max_length=50)),
                ('market_value', models.DecimalField(decimal_places=2, default=0, help_text='Market Value', max_digits=15)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, help_text='Acquisition Cost', max_digits=15)),
                ('use_classification', models.CharField(blank=True, help_text='Gamit (e.g., Kapilya, Pastoral)', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(blank=True, help_text='Local where land is located', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='properties.local')),
            ],
            options={
                'verbose_name': 'Land (Lupa)',
                'verbose_name_plural': 'Lands (Lupa)',
                'ordering': ['local', 'location'],
            },
        ),
    ]
