# Generated by Django 4.2.8 on 2025-12-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0017_alter_local_lcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcode', models.CharField(blank=True, help_text='District code (DCODE)', max_length=10)),
                ('lcode', models.CharField(blank=True, help_text='Local code (LCODE)', max_length=10)),
                ('item_name', models.CharField(help_text='General name/type (e.g., Passenger Van, Pickup)', max_length=255)),
                ('brand', models.CharField(blank=True, help_text='Brand/Make (e.g., Toyota, Mitsubishi)', max_length=100)),
                ('model', models.CharField(blank=True, help_text='Model/Series (e.g., Hiace, L300)', max_length=100)),
                ('plate_number', models.CharField(blank=True, help_text='Plate Number', max_length=20)),
                ('conduction_sticker', models.CharField(blank=True, help_text='Conduction Sticker', max_length=20)),
                ('engine_number', models.CharField(blank=True, help_text='Engine Number', max_length=100)),
                ('chassis_number', models.CharField(blank=True, help_text='Chassis/V.I.N. Number', max_length=100)),
                ('year_model', models.IntegerField(blank=True, help_text='Year Model', null=True)),
                ('color', models.CharField(blank=True, help_text='Color', max_length=50)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, help_text='Acquisition Cost', max_digits=15)),
                ('date_acquired', models.DateField(blank=True, help_text='Date acquired', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Remarks/Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(blank=True, help_text='Local where vehicle is assigned', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='properties.local')),
            ],
            options={
                'verbose_name': 'Vehicle (Sasakyan)',
                'verbose_name_plural': 'Vehicles (Sasakyan)',
                'ordering': ['item_name', 'brand'],
            },
        ),
    ]
