# Generated by Django 4.2.8 on 2025-12-09 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupant_name', models.CharField(help_text='Name of occupant/unit head', max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('date_reported', models.DateField(help_text='Date of report (Petsa ng Pag-uulat)')),
                ('housing_unit_name', models.CharField(help_text='e.g., Unit 22', max_length=100)),
                ('building', models.CharField(help_text='e.g., Abra', max_length=100)),
                ('floor', models.CharField(blank=True, help_text='Floor number', max_length=50)),
                ('unit_number', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Housing Unit',
                'verbose_name_plural': 'Housing Units',
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('property_type', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('square_feet', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('sold', 'Sold'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, help_text='IIN (Item Identification Number)', max_length=50, null=True)),
                ('date_acquired', models.IntegerField(help_text='Year acquired')),
                ('quantity', models.IntegerField(default=1)),
                ('item_name', models.CharField(help_text='Name of item (e.g., Sofa bed)', max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('make', models.CharField(blank=True, help_text='Material composition', max_length=255)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, help_text='Size/Dimension', max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True, help_text="e.g., 'fr. Bodega-maayos'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('housing_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='properties.housingunit')),
            ],
            options={
                'verbose_name': 'Property Inventory',
                'verbose_name_plural': 'Property Inventory',
                'ordering': ['housing_unit', 'item_name'],
                'indexes': [models.Index(fields=['housing_unit', 'item_name'], name='properties__housing_5993f7_idx')],
            },
        ),
    ]
