# Generated by Django 4.2.8 on 2025-12-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('file_hash', models.CharField(help_text='SHA256 hash of file', max_length=64, unique=True)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('records_imported', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('error', 'Error')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Imported File',
                'verbose_name_plural': 'Imported Files',
                'ordering': ['-imported_at'],
            },
        ),
    ]
