# Generated by Django 4.2.8 on 2025-12-09 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('unit_to_unit', 'Unit to Unit'), ('unit_to_storage', 'Unit to Storage (Bodega)'), ('storage_to_unit', 'Storage to Unit'), ('return', 'Return')], default='unit_to_unit', max_length=20)),
                ('to_storage', models.BooleanField(default=False, help_text='Is item transferred to storage/bodega?')),
                ('transferred_by', models.CharField(help_text='Name of person who gave/transferred the item', max_length=255)),
                ('receiver_name', models.CharField(help_text='Name of person who received the item', max_length=255)),
                ('transfer_date', models.DateTimeField(auto_now_add=True, help_text='Date of transfer')),
                ('received_date', models.DateTimeField(blank=True, help_text='Date when item was received', null=True)),
                ('status', models.CharField(choices=[('good', 'Good Condition'), ('damaged', 'Damaged'), ('broken', 'Broken'), ('lost', 'Lost')], default='good', max_length=20)),
                ('reason', models.TextField(help_text='Reason for transfer/pullout')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of items transferred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_transferred_from', to='properties.housingunit')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='properties.propertyinventory')),
                ('to_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_transferred_to', to='properties.housingunit')),
            ],
            options={
                'verbose_name': 'Item Transfer',
                'verbose_name_plural': 'Item Transfers',
                'ordering': ['-transfer_date'],
                'indexes': [models.Index(fields=['transfer_date', 'status'], name='properties__transfe_fab027_idx'), models.Index(fields=['inventory_item', 'transfer_date'], name='properties__invento_df77b8_idx')],
            },
        ),
    ]
