# Generated by Django 4.2.8 on 2025-12-09 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_itemtransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Backup code (8 hex characters)', max_length=20)),
                ('is_used', models.BooleanField(default=False, help_text='Has this code been used?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='When was this code used?', null=True)),
                ('expires_at', models.DateTimeField(help_text='When does this code expire?')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes_list', to='properties.userprofile')),
            ],
            options={
                'verbose_name': 'Backup Code',
                'verbose_name_plural': 'Backup Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_profile', 'code'], name='properties__user_pr_1dcbb7_idx'), models.Index(fields=['user_profile', 'is_used', 'expires_at'], name='properties__user_pr_0a8b03_idx')],
            },
        ),
    ]
