# Generated by Django 4.2.8 on 2025-12-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_backupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinventory',
            name='acquisition_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Original acquisition cost', max_digits=12),
        ),
        migrations.AddField(
            model_name='propertyinventory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total value (acquisition_cost × quantity)', max_digits=12),
        ),
        migrations.AddField(
            model_name='propertyinventory',
            name='net_book_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current net book value after depreciation', max_digits=12),
        ),
        migrations.AddField(
            model_name='propertyinventory',
            name='useful_life',
            field=models.IntegerField(default=5, help_text='Useful life in years'),
        ),
        # Alter the existing integer `date_acquired` to a date column.
        # Use a direct SQL ALTER with a safe USING clause to convert integer year
        # values (e.g. 2020) into a date (e.g. 2020-01-01) using to_date(...,'YYYY').
        migrations.RunSQL(
            sql=(
                "ALTER TABLE properties_propertyinventory "
                "ALTER COLUMN date_acquired TYPE date USING to_date(date_acquired::text, 'YYYY');"
            ),
            reverse_sql=(
                "ALTER TABLE properties_propertyinventory "
                "ALTER COLUMN date_acquired TYPE integer USING EXTRACT(YEAR FROM date_acquired)::integer;"
            ),
        ),
    ]
