# Generated by Django 4.2.8 on 2025-12-09 03:08

from django.db import migrations
from decimal import Decimal
from django.utils.timezone import now


def initialize_net_book_value(apps, schema_editor):
    """Initialize net_book_value for existing inventory items"""
    PropertyInventory = apps.get_model('properties', 'PropertyInventory')
    
    for item in PropertyInventory.objects.all():
        # Calculate amount: acquisition_cost × quantity
        item.amount = (item.acquisition_cost or Decimal('0.00')) * (item.quantity or 1)
        
        # Calculate net book value using simplified straight-line depreciation
        # Formula:
        # Annual Depreciation = Acquisition Cost / Useful Life
        # Net Book Value = Acquisition Cost - Annual Depreciation
        if item.acquisition_cost and item.useful_life > 0:
            annual_depreciation = item.acquisition_cost / item.useful_life
            net_book_value = max(Decimal('0.00'), item.acquisition_cost - annual_depreciation)
            item.net_book_value = net_book_value * (item.quantity or 1)
        else:
            # If no acquisition cost or useful life, use amount as net_book_value
            item.net_book_value = item.amount
        
        # Use update instead of save to avoid triggering the model's save() override
        PropertyInventory.objects.filter(pk=item.pk).update(
            amount=item.amount,
            net_book_value=item.net_book_value
        )


def reverse_initialize_net_book_value(apps, schema_editor):
    """Reverse: Reset net_book_value to 0"""
    PropertyInventory = apps.get_model('properties', 'PropertyInventory')
    PropertyInventory.objects.all().update(net_book_value=Decimal('0.00'), amount=Decimal('0.00'))


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertyinventory_acquisition_cost_and_more'),
    ]

    operations = [
        migrations.RunPython(initialize_net_book_value, reverse_initialize_net_book_value),
    ]
