# Generated by Django 4.2.8 on 2025-12-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_initialize_net_book_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtransfer',
            name='is_scrapped',
            field=models.BooleanField(default=False, help_text='Is this item being scrapped/disposed?'),
        ),
        migrations.AddField(
            model_name='itemtransfer',
            name='scrap_date',
            field=models.DateField(blank=True, help_text='Date when item was scrapped/disposed', null=True),
        ),
        migrations.AddField(
            model_name='itemtransfer',
            name='scrap_reason',
            field=models.CharField(blank=True, help_text='Reason for scrapping (e.g., Beyond repair, Obsolete, No longer needed)', max_length=255),
        ),
        migrations.AddField(
            model_name='itemtransfer',
            name='scrap_sell_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Sell value if scrapped (overrides for accounting)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='itemtransfer',
            name='transfer_type',
            field=models.CharField(choices=[('unit_to_unit', 'Unit to Unit'), ('unit_to_storage', 'Unit to Storage (Bodega)'), ('storage_to_unit', 'Storage to Unit'), ('return', 'Return'), ('scrap', 'Scrap/Disposal')], default='unit_to_unit', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyinventory',
            name='date_acquired',
            field=models.DateField(help_text='Date when item was acquired'),
        ),
    ]
