# Generated by Django 4.2.8 on 2025-12-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_remove_property_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('dcode', models.CharField(help_text='District code (unique identifier)', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='District name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='District description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'Property/Building', 'verbose_name_plural': 'Properties/Buildings'},
        ),
        migrations.AlterField(
            model_name='itemtransfer',
            name='scrap_sell_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Sell value if scrapped in PHP (overrides for accounting)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the property/building'),
        ),
        migrations.AlterField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='province',
            field=models.CharField(blank=True, help_text='Province/State', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyinventory',
            name='acquisition_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Original acquisition cost (PHP)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='propertyinventory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total value in PHP (acquisition_cost × quantity)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='propertyinventory',
            name='net_book_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current net book value after depreciation (PHP)', max_digits=12),
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcode', models.CharField(help_text='Local code (unique identifier)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Local name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Local description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(help_text='District this local belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='locals', to='properties.district')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locals',
                'ordering': ['district', 'name'],
                'unique_together': {('lcode', 'district')},
            },
        ),
    ]
