# Generated by Django 4.2.8 on 2025-12-09 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_district_alter_property_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Property name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Property description')),
                ('address', models.CharField(blank=True, help_text='Property address', max_length=255)),
                ('city', models.CharField(blank=True, help_text='City where property is located', max_length=100)),
                ('property_type', models.CharField(default='Building', help_text='Type of property (e.g., Building, Land, Office, Hall)', max_length=50)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost when property was acquired', max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, help_text='Current estimated value', max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('sold', 'Sold')], default='active', help_text='Property status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(help_text='Local that owns/manages this property', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.local')),
            ],
            options={
                'verbose_name': 'Local Property',
                'verbose_name_plural': 'Local Properties',
                'ordering': ['local', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, help_text='Unique item code', max_length=50)),
                ('item_name', models.CharField(help_text='Name of the item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Item description')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of item')),
                ('date_acquired', models.DateField(help_text='Date when item was acquired')),
                ('brand', models.CharField(blank=True, help_text='Brand/Manufacturer', max_length=100)),
                ('model', models.CharField(blank=True, help_text='Model number', max_length=100)),
                ('make', models.CharField(blank=True, help_text='Make/Type', max_length=100)),
                ('color', models.CharField(blank=True, help_text='Color of item', max_length=50)),
                ('size', models.CharField(blank=True, help_text='Size of item', max_length=50)),
                ('serial_number', models.CharField(blank=True, help_text='Serial number if applicable', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(help_text='Property where item is stored', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='properties.localproperty')),
            ],
            options={
                'verbose_name': 'Local Inventory Item',
                'verbose_name_plural': 'Local Inventory Items',
                'ordering': ['property', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='DistrictProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Property name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Property description')),
                ('address', models.CharField(blank=True, help_text='Property address', max_length=255)),
                ('city', models.CharField(blank=True, help_text='City where property is located', max_length=100)),
                ('property_type', models.CharField(default='Building', help_text='Type of property (e.g., Building, Land, Office, Hall)', max_length=50)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost when property was acquired', max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, help_text='Current estimated value', max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('sold', 'Sold')], default='active', help_text='Property status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(help_text='District that owns/manages this property', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.district')),
            ],
            options={
                'verbose_name': 'District Property',
                'verbose_name_plural': 'District Properties',
                'ordering': ['district', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DistrictInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, help_text='Unique item code', max_length=50)),
                ('item_name', models.CharField(help_text='Name of the item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Item description')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of item')),
                ('date_acquired', models.DateField(help_text='Date when item was acquired')),
                ('brand', models.CharField(blank=True, help_text='Brand/Manufacturer', max_length=100)),
                ('model', models.CharField(blank=True, help_text='Model number', max_length=100)),
                ('make', models.CharField(blank=True, help_text='Make/Type', max_length=100)),
                ('color', models.CharField(blank=True, help_text='Color of item', max_length=50)),
                ('size', models.CharField(blank=True, help_text='Size of item', max_length=50)),
                ('serial_number', models.CharField(blank=True, help_text='Serial number if applicable', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(help_text='Property where item is stored', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='properties.districtproperty')),
            ],
            options={
                'verbose_name': 'District Inventory Item',
                'verbose_name_plural': 'District Inventory Items',
                'ordering': ['property', 'item_name'],
            },
        ),
    ]
