# Generated by Django 4.2.8 on 2025-12-26 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_building_gusali_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buildingyearlyrecord',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='buildingyearlyrecord',
            name='building',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='BuildingYearlyRecord',
        ),
    ]
