# Generated by Django 4.2.8 on 2025-12-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_buildingyearlyrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='district',
            table='district',
        ),
        migrations.AlterModelTable(
            name='local',
            table='lokal',
        ),
    ]
