# Generated by Django 4.2.8 on 2025-12-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_alter_district_table_alter_local_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='lcode',
            field=models.CharField(help_text='Local code (unique identifier)', max_length=10),
        ),
    ]
