# Generated by Django 4.2.8 on 2026-01-16 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_alter_local_lcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingunit',
            options={'ordering': ['-date_reported'], 'verbose_name': 'Housing Unit (Pamayanan)', 'verbose_name_plural': 'Housing Units (Pamayanan)'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pamayanan', 'verbose_name_plural': 'Pamayanan'},
        ),
    ]
