# Generated by Django 4.2.8 on 2026-01-16 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_alter_housingunit_options_alter_property_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Pamayanan',
        ),
        migrations.AlterModelTable(
            name='pamayanan',
            table='properties_pamayanan',
        ),
    ]
