# Generated by Django 4.2.8 on 2026-01-16 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_rename_property_pamayanan_alter_pamayanan_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingunit',
            name='property',
        ),
        migrations.AddField(
            model_name='housingunit',
            name='pamayanan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='housing_units', to='properties.pamayanan'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PamayananBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Building name (e.g. Building 1, New Star)', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pamayanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='properties.pamayanan')),
            ],
            options={
                'verbose_name': 'Pamayanan Building',
                'verbose_name_plural': 'Pamayanan Buildings',
                'ordering': ['pamayanan', 'name'],
                'unique_together': {('pamayanan', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HousingUnitInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('date_acquired', models.DateField()),
                ('quantity', models.IntegerField(default=1)),
                ('item_name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('make', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('useful_life', models.IntegerField(default=5)),
                ('net_book_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('housing_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='properties.housingunit')),
            ],
            options={
                'verbose_name': 'Housing Unit Inventory',
                'verbose_name_plural': 'Housing Unit Inventories',
                'db_table': 'properties_housingunitinventory',
                'ordering': ['housing_unit', 'item_name'],
            },
        ),
        migrations.AddField(
            model_name='housingunit',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Required for condos/high-rise, blank for housing areas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing_units', to='properties.pamayananbuilding'),
        ),
        migrations.AlterField(
            model_name='itemtransfer',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='properties.housingunitinventory'),
        ),
        migrations.DeleteModel(
            name='PropertyInventory',
        ),
    ]
