# Generated by Django 4.2.8 on 2026-01-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='identity_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
