# Generated by Django 4.2.8 on 2026-01-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0002_worker_identity_hash_alter_worker_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='identity_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, unique=True),
        ),
    ]
