# Generated by Django 4.2.8 on 2026-01-15 05:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0003_alter_worker_identity_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='properties_sync', help_text='Source system or trigger', max_length=100)),
                ('triggered_by', models.CharField(blank=True, help_text='Username, system, or scheduler', max_length=150)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial (with conflicts)'), ('failed', 'Failed')], default='success', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('departments_created', models.PositiveIntegerField(default=0)),
                ('sections_created', models.PositiveIntegerField(default=0)),
                ('workers_created', models.PositiveIntegerField(default=0)),
                ('buildings_created', models.PositiveIntegerField(default=0)),
                ('offices_created', models.PositiveIntegerField(default=0)),
                ('assignments_created', models.PositiveIntegerField(default=0)),
                ('conflicts_detected', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('WORKER_IDENTITY', 'Worker Identity Conflict'), ('DEPARTMENT_MISMATCH', 'Department Mismatch'), ('SECTION_MISMATCH', 'Section Mismatch'), ('OFFICE_ASSIGNMENT', 'Office Assignment Conflict'), ('HOUSING_ASSIGNMENT', 'Housing Assignment Conflict'), ('BUILDING_MISMATCH', 'Building Mismatch')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('identity_hash', models.CharField(db_index=True, max_length=64)),
                ('existing_value', models.TextField()),
                ('incoming_value', models.TextField()),
                ('source', models.CharField(default='properties_sync', max_length=100)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='admin_core.worker')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conflict_type', 'resolved'], name='admin_core__conflic_e3f5f3_idx'), models.Index(fields=['identity_hash'], name='admin_core__identit_27db90_idx')],
            },
        ),
    ]
