# Generated by Django 4.2.8 on 2026-01-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0004_syncrun_syncconflict'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictFieldDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('decision', models.CharField(choices=[('existing', 'Keep Existing'), ('incoming', 'Use Incoming')], default='existing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_decisions', to='admin_core.syncconflict')),
            ],
            options={
                'unique_together': {('conflict', 'field_name')},
            },
        ),
    ]
