# Generated by Django 4.2.8 on 2026-01-16 06:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0005_conflictfielddecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['site__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HousingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('is_multi_building', models.BooleanField(default=False, help_text='Does this pamayanan have multiple buildings?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HousingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_label', models.CharField(help_text='Unit identifier (11-03, Unit 22, House #5)', max_length=100)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['site__name', 'building__name', 'unit_label'],
            },
        ),
        migrations.AlterModelOptions(
            name='syncrun',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='syncconflict',
            name='admin_core__conflic_e3f5f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='syncconflict',
            name='admin_core__identit_27db90_idx',
        ),
        migrations.RenameField(
            model_name='syncrun',
            old_name='assignments_created',
            new_name='housing_buildings_created',
        ),
        migrations.RenameField(
            model_name='syncrun',
            old_name='buildings_created',
            new_name='housing_sites_created',
        ),
        migrations.RenameField(
            model_name='syncrun',
            old_name='departments_created',
            new_name='housing_units_created',
        ),
        migrations.AlterUniqueTogether(
            name='conflictfielddecision',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='syncrun',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='syncrun',
            name='duration_ms',
        ),
        migrations.RemoveField(
            model_name='syncrun',
            name='offices_created',
        ),
        migrations.RemoveField(
            model_name='syncrun',
            name='sections_created',
        ),
        migrations.RemoveField(
            model_name='syncrun',
            name='source',
        ),
        migrations.RemoveField(
            model_name='syncrun',
            name='triggered_by',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='date_ended',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='conflictfielddecision',
            name='chosen_value',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conflictfielddecision',
            name='decision_type',
            field=models.CharField(choices=[('keep_existing', 'Keep Existing'), ('use_incoming', 'Use Incoming'), ('manual_input', 'Manual Input')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conflictfielddecision',
            name='resolved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conflictfielddecision',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='housingunitassignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='syncconflict',
            name='conflict_type',
            field=models.CharField(choices=[('WORKER_IDENTITY', 'Worker Identity Conflict'), ('DEPARTMENT_MISMATCH', 'Department Mismatch'), ('SECTION_MISMATCH', 'Section Mismatch'), ('ADMIN_BUILDING_MISMATCH', 'Admin Building Mismatch'), ('HOUSING_SITE_MISMATCH', 'Housing Site Mismatch'), ('HOUSING_BUILDING_MISMATCH', 'Housing Building Mismatch'), ('HOUSING_ASSIGNMENT', 'Housing Assignment Conflict')], max_length=50),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='identity_hash',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='housingunit',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='admin_core.housingbuilding'),
        ),
        migrations.AddField(
            model_name='housingunit',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='admin_core.housingsite'),
        ),
        migrations.AddField(
            model_name='housingbuilding',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='admin_core.housingsite'),
        ),
        migrations.RemoveField(
            model_name='conflictfielddecision',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='conflictfielddecision',
            name='decision',
        ),
        migrations.AlterField(
            model_name='housingunitassignment',
            name='housing_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_assignments', to='admin_core.housingunit'),
        ),
        migrations.AlterUniqueTogether(
            name='housingbuilding',
            unique_together={('site', 'name')},
        ),
    ]
