# Generated by Django 4.2.8 on 2025-12-26 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0015_alter_buildingyearlyrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'A - Kapilya'), ('B', 'B - Pastoral/Caretaker'), ('C', 'C - Ministerial/Finance/Secretariat'), ('D', 'D - Other Buildings')], help_text='Building code (A, B, C, D)', max_length=5)),
                ('name', models.CharField(help_text='Building name (e.g., KAPILYA, GUARD HOUSE)', max_length=255)),
                ('classification', models.CharField(blank=True, help_text='Building classification (e.g., A-3, A-PH, ADL-1)', max_length=50)),
                ('is_donated', models.BooleanField(default=False, help_text='Whether the building was donated (HANDOG)')),
                ('donation_date', models.DateField(blank=True, help_text='Date when building was donated (PETSA INIHANDOG)', null=True)),
                ('ownership_date', models.DateField(blank=True, help_text='Date when building was acquired/owned (PETSA MAYARI)', null=True)),
                ('constructor', models.CharField(blank=True, help_text='Builder/Constructor (PAGAWA)', max_length=255)),
                ('capacity', models.IntegerField(blank=True, help_text='Building capacity (number of people)', null=True)),
                ('original_cost', models.DecimalField(decimal_places=2, default=0, help_text='Original cost of building (PHP)', max_digits=15)),
                ('current_total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Current total cost including all additions (PHP)', max_digits=15)),
                ('year_covered', models.IntegerField(default=2024, help_text='Year covered by the report')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(blank=True, help_text='Local where building is located', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gusali_buildings', to='properties.local')),
            ],
            options={
                'verbose_name': 'Building (Gusali)',
                'verbose_name_plural': 'Buildings (Gusali)',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BuildingYearlyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year of this record')),
                ('cost_last_year', models.DecimalField(decimal_places=2, default=0, help_text='Cost from previous year (COST LAST YEAR)', max_digits=15)),
                ('construction_cost', models.DecimalField(decimal_places=2, default=0, help_text='Construction additions (CONSTRUCTION)', max_digits=15)),
                ('renovation_cost', models.DecimalField(decimal_places=2, default=0, help_text='Renovation costs (RENOVATION)', max_digits=15)),
                ('general_repair_cost', models.DecimalField(decimal_places=2, default=0, help_text='General repair costs (GENERAL REPAIR)', max_digits=15)),
                ('other_additions_cost', models.DecimalField(decimal_places=2, default=0, help_text='Other additions (OTHER)', max_digits=15)),
                ('total_added', models.DecimalField(decimal_places=2, default=0, help_text='Total additions (calculated)', max_digits=15)),
                ('broken_removed_part', models.CharField(blank=True, help_text='Description of broken/removed parts (PART)', max_length=255)),
                ('broken_removed_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost of broken/removed items (COST)', max_digits=15)),
                ('year_end_total', models.DecimalField(decimal_places=2, default=0, help_text='Total cost at end of year (TOTAL)', max_digits=15)),
                ('remarks', models.TextField(blank=True, help_text='Remarks for this year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(help_text='Building this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='yearly_records', to='gusali.building')),
            ],
            options={
                'verbose_name': 'Building Yearly Record',
                'verbose_name_plural': 'Building Yearly Records',
                'ordering': ['-year', 'building'],
                'indexes': [models.Index(fields=['building', 'year'], name='gusali_buil_buildin_deb27d_idx')],
                'unique_together': {('building', 'year')},
            },
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['code', 'local'], name='gusali_buil_code_e9d23e_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['local', 'year_covered'], name='gusali_buil_local_i_627dd2_idx'),
        ),
    ]
