# Generated by Django 4.2.8 on 2025-12-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gusali', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='dcode',
            field=models.CharField(blank=True, help_text='District code (DCODE)', max_length=10),
        ),
        migrations.AddField(
            model_name='building',
            name='lcode',
            field=models.CharField(blank=True, help_text='Local code (LCODE)', max_length=10),
        ),
    ]
