# Generated by Django 4.2.8 on 2025-12-11 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcode', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcode', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locals', to='national.district')),
            ],
            options={
                'unique_together': {('district', 'lcode')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(blank=True, max_length=128)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='national.local')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('local', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_total', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('p2_total', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('p3_total', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('p4_total', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('p5_total', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('total_summary', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='national.report')),
            ],
        ),
        migrations.CreateModel(
            name='Page5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('qty', models.IntegerField(null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page5', to='national.report')),
            ],
        ),
        migrations.CreateModel(
            name='Page4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('depreciation', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('net', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page4', to='national.report')),
            ],
        ),
        migrations.CreateModel(
            name='Page3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('qty', models.IntegerField(null=True)),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page3', to='national.report')),
            ],
        ),
        migrations.CreateModel(
            name='Page2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_value', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('additions', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('net', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page2', to='national.report')),
            ],
        ),
        migrations.CreateModel(
            name='Page1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('prior', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('additions', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('net', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page1', to='national.report')),
            ],
        ),
    ]
