# Generated by Django 4.2.8 on 2025-12-12 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('national', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('dcode', models.CharField(blank=True, max_length=5)),
                ('lcode', models.CharField(blank=True, max_length=10)),
                ('lokal', models.CharField(blank=True, max_length=255)),
                ('chapel_class', models.CharField(blank=True, max_length=50)),
                ('seating_capacity', models.IntegerField(blank=True, null=True)),
                ('offered', models.BooleanField(default=False)),
                ('date_offered', models.DateField(blank=True, null=True)),
                ('date_built', models.DateField(blank=True, null=True)),
                ('funded_by', models.CharField(blank=True, max_length=128)),
                ('original_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('last_year_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('add_construction', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('add_renovation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('add_general_repair', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('add_others', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_added', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('deduction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('deduction_reason', models.CharField(blank=True, max_length=255)),
                ('total_cost_this_year', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapels', to='national.report')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(blank=True, max_length=255)),
                ('office_class', models.CharField(blank=True, max_length=50)),
                ('date_built', models.DateField(blank=True, null=True)),
                ('old_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('add_this_year', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sub_this_year', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='national.report')),
            ],
        ),
        migrations.CreateModel(
            name='OtherBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(blank=True, max_length=255)),
                ('building_class', models.CharField(blank=True, max_length=50)),
                ('date_built', models.DateField(blank=True, null=True)),
                ('add_this_year', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sub_this_year', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_buildings', to='national.report')),
            ],
        ),
        migrations.CreateModel(
            name='Page1Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_chapels', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_pastoral', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_offices', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_other_buildings', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page1_summary', to='national.report')),
            ],
        ),
        migrations.CreateModel(
            name='PastoralHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('house_class', models.CharField(blank=True, max_length=50)),
                ('date_built', models.DateField(blank=True, null=True)),
                ('old_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('add_this_year', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sub_this_year', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastoral_houses', to='national.report')),
            ],
        ),
        migrations.DeleteModel(
            name='Page1',
        ),
    ]
