# Generated by Django 4.2.8 on 2025-12-12 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('national', '0002_chapel_officebuilding_otherbuilding_page1summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaukulan', models.CharField(blank=True, max_length=255, null=True)),
                ('iin_code', models.CharField(blank=True, max_length=50, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaukulan', models.CharField(blank=True, max_length=255, null=True)),
                ('iin_code', models.CharField(blank=True, max_length=50, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('approval_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAddedSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRemoved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_place', models.CharField(blank=True, max_length=255, null=True)),
                ('iin_code', models.CharField(blank=True, max_length=50, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRemovedSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('building_on_land', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(default='existing', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LandSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('no_land_type', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_years', models.CharField(blank=True, max_length=50, null=True)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plant_type', models.CharField(blank=True, max_length=1, null=True)),
                ('last_year_qty', models.IntegerField(blank=True, null=True)),
                ('last_year_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('this_year_qty', models.IntegerField(blank=True, null=True)),
                ('this_year_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sub_qty', models.IntegerField(blank=True, null=True)),
                ('sub_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_value_current', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_type', models.CharField(max_length=255)),
                ('plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('year_model', models.IntegerField(blank=True, null=True)),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('assigned_user', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('category', models.CharField(default='existing', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='page3',
            name='report',
        ),
        migrations.RemoveField(
            model_name='page4',
            name='report',
        ),
        migrations.RemoveField(
            model_name='page5',
            name='report',
        ),
        migrations.AlterField(
            model_name='report',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reportsummary',
            name='p1_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='reportsummary',
            name='p2_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='reportsummary',
            name='p3_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='reportsummary',
            name='p4_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='reportsummary',
            name='p5_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='reportsummary',
            name='total_summary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.DeleteModel(
            name='Page2',
        ),
        migrations.DeleteModel(
            name='Page3',
        ),
        migrations.DeleteModel(
            name='Page4',
        ),
        migrations.DeleteModel(
            name='Page5',
        ),
        migrations.AddField(
            model_name='vehiclesummary',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_summary', to='national.report'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='national.report'),
        ),
        migrations.AddField(
            model_name='plantsummary',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant_summary', to='national.report'),
        ),
        migrations.AddField(
            model_name='plant',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='national.report'),
        ),
        migrations.AddField(
            model_name='landsummary',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land_summary', to='national.report'),
        ),
        migrations.AddField(
            model_name='land',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='national.report'),
        ),
        migrations.AddField(
            model_name='itemssummary',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='items_summary', to='national.report'),
        ),
        migrations.AddField(
            model_name='itemremovedsummary',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='items_removed_summary', to='national.report'),
        ),
        migrations.AddField(
            model_name='itemremoved',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_removed', to='national.report'),
        ),
        migrations.AddField(
            model_name='itemaddedsummary',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='items_added_summary', to='national.report'),
        ),
        migrations.AddField(
            model_name='itemadded',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_added', to='national.report'),
        ),
        migrations.AddField(
            model_name='item',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='national.report'),
        ),
    ]
