# Generated by Django 4.2.8 on 2025-12-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national', '0003_item_itemadded_itemaddedsummary_itemremoved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='lcode',
            field=models.CharField(max_length=20),
        ),
    ]
