# Generated by Django 4.2.8 on 2025-12-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national', '0004_alter_local_lcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherbuilding',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='otherbuilding',
            name='old_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
